[package]
name = "RustDemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 在创建本项目的机器上可以不配置，但是在项目被其它机器在仓库中拉取后，会找不到主入口，所以需要配置bin
[[bin]]
name = "hello"
path = "src/hello.rs"
